config/routes.rb
Rails.application.routes.draw do


  post 'favorites/new'
  get 'degree_requirments/find'

  get 'favorites/search'

  get 'favorites/edit'


  post 'past_courses/new'
  delete "past_courses/delete"
  get 'past_courses/edit'


  get 'welcome/index'

  get 'about/aboutus'

  root 'welcome#index'
  devise_for :users, :controllers => { registrations: 'registrations' }



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
#Jason Kline created this page on 11/29/2016

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
#Jason Kline created this page on 11/29/2016
#Modifications made by Yuzhao Li on 11/30/2016
class Course < ApplicationRecord
  has_many :sections
  has_many :past_courses
  belongs_to :past_course
end

app/models/favorite.rb
#Jason Kline created this page on 11/29/2016
#Modifications made by Yuzhao Li on 11/30/2016
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :section, optional: true
end

app/models/instructor.rb
#Jason Kline created this page on 11/29/2016
class Instructor < ApplicationRecord
end

app/models/past_course.rb
#Jason Kline created this page on 11/29/2016

class PastCourse < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :course, optional:true
end

app/models/section.rb
#Jason Kline created this page on 11/29/2016

class Section < ApplicationRecord
  has_many :favorites
end

app/models/user.rb
#Jason Kline created this page on 11/29/2016
#Modifications made by Yuzhao Li on 11/30/2016

class User < ApplicationRecord
  has_many :favorites
  has_many :past_courses
  attr_accessor :major


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
#Jason Kline created this page on 11/28/2016
#
#Modifications made by Jason Kline on 11/30/2016
class AboutController < ApplicationController
  layout 'application'
  def aboutus
  end
end

app/controllers/application_controller.rb
#Jason Kline created this page on 11/28/2016
#
#Modifications made by Jason Kline on 11/30/2016
class ApplicationController < ActionController::Base
  layout "registerLayout"
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/favorites_controller.rb
#Brett Boehmer created this page on 11/28/2016
#
#Modifications made by Jason Kline on 11/30/2016
#Modifications made by Brett Boehmer on 12/1/2016
class FavoritesController < ApplicationController

  layout 'application'
  def search
      @courses = Course.all
      @favs=4
  end

  def edit
      @courses = Course.all
      @sections = Section.all
      @instructors = Instructor.all
  end

  def new
    @favorite = Favorite.create :section_id => params[:section_id], :user_id => params[:user_id]
    redirect_to "/favorites/edit"
  end

  private

  def favorite_params
    params.permit(:section_id, :user_id)
  end
end

app/controllers/past_courses_controller.rb
#Jason Kline created this page on 11/28/2016
#
#Modifications made by Jason Kline on 11/30/2016
#Modifications made by Brett Boehmer on 12/1/2016
#Modifications made by Yuzhao Li on 12/1/2016
class PastCoursesController < ApplicationController

  layout "application"
  def edit
    @courses = Course.all
    @past_course = PastCourse.all
  end

  def new
    @add_past_course = PastCourse.create :course_id => params[:course_id], :user_id => params[:user_id]
    redirect_to past_courses_edit_path
  end

  def delete
    @deleted_course = PastCourse.destroy(params[:course_id])
    redirect_to past_courses_edit_path
  end
  private

  def past_course_params
    params.permit(:user_id, :course_id)
  end


end

app/controllers/registrations_controller.rb
#Yuzhao Li created this page on 11/29/2016
#
#Modifications made by Jason Kline on 11/30/2016
class RegistrationsController < Devise::RegistrationsController

  layout "registerLayout"

  private

  def sign_up_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :major)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/welcome_controller.rb
#Jason Kline created this page on 11/28/2016
#
#Modifications made by Jason Kline on 11/30/2016
class WelcomeController < ApplicationController
  layout "application"

  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/degree_requirements_helper.rb
module DegreeRequirementsHelper
end

app/helpers/degree_requirments_helper.rb
module DegreeRequirmentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/past_courses_helper.rb
module PastCoursesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!--Jason Kline created this page on 11/29/2016
Modifications made by Yuzhao Li on 11/30/2016
-->
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProjectWebNinjas</title>
    <%= csrf_meta_tags %>

    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/semantic/out/semantic.min.css">
    <link rel="stylesheet" href="/stylesheets/style.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'navFunc' %>
    <script type="text/javascript" src="/semantic/out/semantic.min.js"></script>

  </head>
  <div class="container">
    <h1 id = "cseSchTitle">CSE Schedulizer</h1>
  </div>

  <body>
    <%= render :partial => 'shared/navbar' %>
<button class="ui icon button" id = "showNav">
  <i class="list layout icon"></i>
</button>
    <%= yield %>
  </body>
</html>

app/views/layouts/registerLayout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProjectWebNinjas</title>
    <%= csrf_meta_tags %>

    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/semantic/out/semantic.min.css">
    <link rel="stylesheet" href="/stylesheets/style.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'navFunc' %>
    <script type="text/javascript" src="/semantic/out/semantic.min.js"></script>

  </head>
  <div class="container">
    <h1 id = "cseSchTitle">CSE Schedulizer</h1>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!-- Blake Howard, 11082016 -->

    <div class="ui left demo vertical inverted sidebar labeled icon menu">

         <%= link_to(welcome_index_path, :class => 'item') do %>
            <i class="star icon"></i>Favorites
          <% end %>

      <%= link_to(favorites_edit_path, :class => 'item') do %>
        <i class="search icon"></i>Search
      <% end %>


   <%= link_to(degree_requirments_find_path, :class => 'item') do %>
        <i class="book icon"></i>Degree Requirements
      <% end %>

    <%= link_to(past_courses_edit_path, :class => 'item') do %>
         <i class="edit icon"></i>Edit Profile
      <% end %>

   <%= link_to(about_aboutus_path, :class => 'item') do %>
        <i class="info circle icon"></i>AboutUs
      <% end %>


    </div>